[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[build.environment]
  NODE_VERSION = "18"

# Domain and redirect settings
[[redirects]]
  from = "https://www.amarredeamorfuertes.com/*"
  to = "https://amarredeamorfuertes.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://amarredeamorfuertes.com/*"
  to = "https://amarredeamorfuertes.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.amarredeamorfuertes.com/*"
  to = "https://amarredeamorfuertes.com/:splat"
  status = 301
  force = true

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"
    X-Robots-Tag = "index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=86400"

# Edge functions (if needed)
[functions]
  directory = "netlify/functions"

# Form handling
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true

# Security
[context.production.environment]
  HUGO_ENV = "production"