#!/bin/sh

files="/Users/usuario/landingpage/blog/amarres-con-aceites-esenciales.html /Users/usuario/landingpage/blog/amarres-con-agua-de-luna.html /Users/usuario/landingpage/blog/amarres-con-azucar.html /Users/usuario/landingpage/blog/amarres-con-canela.html /Users/usuario/landingpage/blog/amarres-con-colores-especificos.html /Users/usuario/landingpage/blog/amarres-con-cristales-cuarzo.html /Users/usuario/landingpage/blog/amarres-con-elementos-especificos-naturaleza.html /Users/usuario/landingpage/blog/amarres-con-elementos-naturales.html /Users/usuario/landingpage/blog/amarres-con-elementos-temporadas-especificas.html /Users/usuario/landingpage/blog/amarres-con-fases-lunares-especificas.html /Users/usuario/landingpage/blog/amarres-con-fotografias.html /Users/usuario/landingpage/blog/amarres-con-hierbas-aromaticas.html /Users/usuario/landingpage/blog/amarres-con-incienso.html /Users/usuario/landingpage/blog/amarres-con-miel.html /Users/usuario/landingpage/blog/amarres-con-musica-sonidos.html /Users/usuario/landingpage/blog/amarres-con-numeros-sagrados.html /Users/usuario/landingpage/blog/amarres-con-petalos-de-rosa.html /Users/usuario/landingpage/blog/amarres-con-piedras-preciosas.html /Users/usuario/landingpage/blog/amarres-con-sal.html /Users/usuario/landingpage/blog/amarres-con-velas-rojas.html /Users/usuario/landingpage/blog/amarres-de-amor-efectivos.html /Users/usuario/landingpage/blog/amarres-de-pareja.html /Users/usuario/landingpage/blog/conjuros-de-amor.html /Users/usuario/landingpage/blog/hechizos-para-enamorar.html /Users/usuario/landingpage/blog/retorno-de-pareja.html /Users/usuario/landingpage/blog/brujos-en-consulta-gratis/amarres-de-amor-en-consulta-gratis.html /Users/usuario/landingpage/blog/brujos-en-consulta-gratis/brujos-en-consulta-gratis.html /Users/usuario/landingpage/blog/brujos-en-consulta-gratis/como-consultar-gratis-un-brujo.html /Users/usuario/landingpage/blog/brujos-en-consulta-gratis/espiritistas-en-consulta-gratis.html /Users/usuario/landingpage/blog/brujos-en-consulta-gratis/los-mejores-brujos-en-consultas-gratis.html /Users/usuario/landingpage/blog/como-hacer/como-hacer-amarres-de-amor-que-funcionen.html /Users/usuario/landingpage/styles.css /Users/usuario/landingpage/mobile-optimization.css"

for file in $files; do
  sed -i '' '/background: white;/d' "$file"
  sed -i '' '/background: rgb(248, 249, 250);/d' "$file"
  sed -i '' '/background: linear-gradient(135deg, var(--background-light) 0%, white 100%);/d' "$file"
  sed -i '' '/background: var(--background-light);/d' "$file"
  sed -i '' '/background: linear-gradient(135deg, #FFF8E1 0%, #FFEBEE 100%);/d' "$file"
done